app:
  is-secured: true
  api-prefix: /api/v1

spring:
  application:
    name: delivery-kata
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_kata_db
    username: selim
    password: pwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      enabled: true # in case u wanna enable compose from being managed by Spring, set it to true ;)
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
    fr:
      carrefour:
        kata: debug